#!/bin/bash

FILE_TO_OPEN="$1"

if [ -n "$FILE_TO_OPEN" ]; then
    if [ ! -f "$FILE_TO_OPEN" ]; then
        :
    else
        if grep -q "ACTION:EVENTS:GLITCHEVENT" "$FILE_TO_OPEN"; then
            echo "ACTION:EVENTS:GLITCHEVENT"
            exit 0
        fi
        if grep -q "ACTION:EVENTS:ENDGAME" "$FILE_TO_OPEN"; then
            echo "ACTION:EVENTS:ENDGAME"
            exit 0
        fi
    fi
fi

exec /bin/busybox vi "$@"